# Dockerfile.node

# Используем официальный образ Node.js
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь код приложения
COPY . .

# Указываем команду для запуска Node.js приложения
# Предполагается, что точка входа - avitoReader.js
CMD ["node", "avitoReader.js"]
