# Dockerfile.python

# Используем официальный образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файл зависимостей
COPY requirements.txt ./

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код приложения
COPY . .

# Указываем команду для запуска Python приложения
# Предполагается, что точка входа - telegram-bot.py
CMD ["python", "telegram-bot.py"]
